<a href="https://colab.research.google.com/github/Ayush04H/Machine_Leaarning2/blob/main/CarRentalNew.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# **Import Dataset**

In [2]:
dataset=pd.read_csv('CarRentalData.csv')
dataset.head()

fuelType  rating  renterTripsTaken  reviewCount      location.city  \
0  GASOLINE     5.0                 1            1              Miami   
1  GASOLINE     NaN                 0            0           Monument   
2  GASOLINE     NaN                 0            0  Sunny Isles Beach   
3  GASOLINE     5.0                 3            2  Sunny Isles Beach   
4       NaN     4.8                21           15        Miami Beach   

  location.country  location.latitude  location.longitude location.state  \
0               US          25.762867          -80.189340             FL   
1               US          39.065143         -104.833966             CO   
2               US          25.952209          -80.120557             FL   
3               US          25.952512          -80.119771             FL   
4               US          25.791807          -80.128564             FL   

   owner.id  rate.daily   vehicle.make vehicle.model  vehicle.year  \
0    864946        1500    Rolls Royce         Ghost          2011   
1  15248243        1485           Ford       Mustang          2020   
2    864946        1400  Mercedes-Benz       G-Class          2015   
3    864946        1200   Aston Martin    V8 Vantage          2013   
4   9541863        1199    Lamborghini       Huracan          2019   

  vehicle.type  
0          car  
1          car  
2          suv  
3          car  
4          car

**To Check for the null values**

In [3]:
dataset.isnull().sum()

fuelType               80
rating                521
renterTripsTaken        0
reviewCount             0
location.city           0
location.country        0
location.latitude       0
location.longitude      0
location.state          0
owner.id                0
rate.daily              0
vehicle.make            0
vehicle.model           0
vehicle.year            0
vehicle.type            0
dtype: int64

# **No Of Rows And Columns**

In [4]:
dataset.shape

(6097, 15)

# **Description of Data**

In [5]:
dataset.describe()

rating  renterTripsTaken  reviewCount  location.latitude  \
count  5576.000000       6097.000000  6097.000000        6097.000000   
mean      4.920109         33.451206    28.431852          35.511774   
std       0.180109         41.660525    34.928912           6.315087   
min       1.000000          0.000000     0.000000          21.272565   
25%       4.900000          5.000000     4.000000          32.041299   
50%       5.000000         18.000000    16.000000          35.182422   
75%       5.000000         46.000000    40.000000          39.940748   
max       5.000000        395.000000   321.000000          64.893610   

       location.longitude      owner.id   rate.daily  vehicle.year  
count         6097.000000  6.097000e+03  6097.000000   6097.000000  
mean           -99.143961  5.797009e+06    94.456618   2015.351156  
std             20.176938  4.696837e+06    95.759326      4.013862  
min           -158.165693  5.105000e+03    20.000000   1955.000000  
25%           -117.102528  1.506983e+06    45.000000   2014.000000  
50%            -95.382956  4.609659e+06    69.000000   2016.000000  
75%            -81.727800  9.468747e+06   112.000000   2018.000000  
max            -68.823637  1.581088e+07  1500.000000   2020.000000

**Dealing with the Null data**

In [6]:
dataset['fuelType'].fillna(method ='ffill',  inplace = True)
dataset['rating'].fillna(method ='ffill',  inplace = True)
dataset.isnull().sum()

fuelType              0
rating                0
renterTripsTaken      0
reviewCount           0
location.city         0
location.country      0
location.latitude     0
location.longitude    0
location.state        0
owner.id              0
rate.daily            0
vehicle.make          0
vehicle.model         0
vehicle.year          0
vehicle.type          0
dtype: int64

# Encoding IndeDependent Variable

# **Encoding The Dependent Variable**

In [7]:
dataset['vehicle.type'].value_counts()

car        3659
suv        1714
truck       382
minivan     232
van         110
Name: vehicle.type, dtype: int64

In [8]:
dataset.replace({'vehicle.type':{'car':0,'suv':1,'minivan':2,'truck':3,'van':4},'location.country':{'US':1}},inplace=True)
dataset.head()

fuelType  rating  renterTripsTaken  reviewCount      location.city  \
0  GASOLINE     5.0                 1            1              Miami   
1  GASOLINE     5.0                 0            0           Monument   
2  GASOLINE     5.0                 0            0  Sunny Isles Beach   
3  GASOLINE     5.0                 3            2  Sunny Isles Beach   
4  GASOLINE     4.8                21           15        Miami Beach   

   location.country  location.latitude  location.longitude location.state  \
0                 1          25.762867          -80.189340             FL   
1                 1          39.065143         -104.833966             CO   
2                 1          25.952209          -80.120557             FL   
3                 1          25.952512          -80.119771             FL   
4                 1          25.791807          -80.128564             FL   

   owner.id  rate.daily   vehicle.make vehicle.model  vehicle.year  \
0    864946        1500    Rolls Royce         Ghost          2011   
1  15248243        1485           Ford       Mustang          2020   
2    864946        1400  Mercedes-Benz       G-Class          2015   
3    864946        1200   Aston Martin    V8 Vantage          2013   
4   9541863        1199    Lamborghini       Huracan          2019   

   vehicle.type  
0             0  
1             0  
2             1  
3             0  
4             0

In [9]:
dataset['vehicle.type'].value_counts()

0    3659
1    1714
3     382
2     232
4     110
Name: vehicle.type, dtype: int64

In [10]:
x=dataset.drop(columns='vehicle.type',axis=1)
y=dataset['vehicle.type']

In [11]:
print(x)

      fuelType  rating  renterTripsTaken  reviewCount      location.city  \
0     GASOLINE    5.00                 1            1              Miami   
1     GASOLINE    5.00                 0            0           Monument   
2     GASOLINE    5.00                 0            0  Sunny Isles Beach   
3     GASOLINE    5.00                 3            2  Sunny Isles Beach   
4     GASOLINE    4.80                21           15        Miami Beach   
...        ...     ...               ...          ...                ...   
6092  GASOLINE    5.00                 6            4     Salt Lake City   
6093  GASOLINE    4.86                 9            7     Salt Lake City   
6094  GASOLINE    5.00                13           13            Orlando   
6095  GASOLINE    4.98                65           54             Edmond   
6096  GASOLINE    4.94                41           36             Irvine   

      location.country  location.latitude  location.longitude location.state  \
0      

In [12]:
print(y)

0       0
1       0
2       1
3       0
4       0
       ..
6092    0
6093    0
6094    0
6095    0
6096    0
Name: vehicle.type, Length: 6097, dtype: int64


In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0,4,8,11,12])],remainder='passthrough')
x=ct.fit_transform(x)

In [14]:
print(x)

  (0, 2)	1.0
  (0, 552)	1.0
  (0, 984)	1.0
  (0, 1064)	1.0
  (0, 1301)	1.0
  (0, 1601)	5.0
  (0, 1602)	1.0
  (0, 1603)	1.0
  (0, 1604)	1.0
  (0, 1605)	25.762867
  (0, 1606)	-80.18934
  (0, 1607)	864946.0
  (0, 1608)	1500.0
  (0, 1609)	2011.0
  (1, 2)	1.0
  (1, 576)	1.0
  (1, 980)	1.0
  (1, 1035)	1.0
  (1, 1390)	1.0
  (1, 1601)	5.0
  (1, 1604)	1.0
  (1, 1605)	39.065143
  (1, 1606)	-104.833966
  (1, 1607)	15248243.0
  (1, 1608)	1485.0
  :	:
  (6095, 1059)	1.0
  (6095, 1140)	1.0
  (6095, 1601)	4.98
  (6095, 1602)	65.0
  (6095, 1603)	54.0
  (6095, 1604)	1.0
  (6095, 1605)	35.651699
  (6095, 1606)	-97.55544
  (6095, 1607)	7472911.0
  (6095, 1608)	20.0
  (6095, 1609)	2009.0
  (6096, 2)	1.0
  (6096, 419)	1.0
  (6096, 979)	1.0
  (6096, 1059)	1.0
  (6096, 1552)	1.0
  (6096, 1601)	4.94
  (6096, 1602)	41.0
  (6096, 1603)	36.0
  (6096, 1604)	1.0
  (6096, 1605)	33.646327
  (6096, 1606)	-117.749031
  (6096, 1607)	8853685.0
  (6096, 1608)	20.0
  (6096, 1609)	2017.0


# **Split Test and Train data**

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

# **Feature scaling**

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=False)
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
x=sc.transform(x)

# **Training The Model**

In [17]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

# **Predicting of The Test Set**

In [18]:
y_pred=classifier.predict(X_test)

# **Confusion Metrics and accuracy score**

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test, y_pred)
print('The Accuracy for the Model will be :',acc*100,'%')

[[891  10   0   9   1]
 [ 22 399   0   6   0]
 [  1   0  58   0   0]
 [ 22   4   0  76   0]
 [  6   1   1   4  14]]
The Accuracy for the Model will be : 94.29508196721311 %


# **Making A Predictive System**

In [20]:
n=int(input("Enter the Number of Data Upto which u want to check the data in X_test"))
for a in range(0,n+1):
  inp=X_test[a]
  prediction=classifier.predict(inp)
  print(prediction)
  if(prediction==0):
    print("The Vehicle Rented is a Car as it is mapped with value ",prediction)
  elif(prediction==1):
    print("The Vehicle Rented is a SUV as it is mapped with value ",prediction)
  elif(prediction==2):
    print("The Vehicle Rented is a minivan as it is mapped with value ",prediction)
  elif(prediction==3):
    print("The Vehicle Rented is a truck as it is mapped with value ",prediction)
  elif(prediction==4):
    print("The Vehicle Rented is a van as it is mapped with value ",prediction)
  else:
    print('Unable to Predict')

Enter the Number of Data Upto which u want to check the data in X_test250
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[3]
The Vehicle Rented is a truck as it is mapped with value  [3]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[1]
The Vehicle Rented is a 